#!/usr/bin/env bash
# To ensure Nginx is configured to listen on port 80 and fixes any issues.

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
