#!/usr/bin/env bash
# A shorter version of your the first task meeting the stated requirements

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
printf "\n"
