#!/usr/bin/env bash
if ! dpkg -l nginx &> /dev/null; then apt-get update && apt-get install -y nginx; fi
nginx -t && nginx -s reload || (sed -i 's/^.*listen.*$/    listen 80;/g' \
/etc/nginx/sites-available/default && ln -sf /etc/nginx/sites-available/default \
/etc/nginx/sites-enabled/default && nginx -s reload)

