#!/bin/bash

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root." 
   exit 1
fi

# Using ifconfig
echo "Active IPv4 IPs using ifconfig:"
ifconfig | grep -oP 'inet \K[\d.]+'

# Using ip
echo -e "\nActive IPv4 IPs using ip:"
ip -4 addr show | awk '/inet / {print $2}' | cut -d'/' -f1
