#!/bin/bash/env bash
# Bash script to configure Nginx to run as nginx user and listen on port 8080

sed -i 's/user\s\+[^;]\+/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s\+[^:]\+:80;/listen *:8080;/' /etc/nginx/sites-available/default
